import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'
import { REPO_ROOT } from '../lib/paths.mts'
import { isMainModule } from '../lib/run-node.mts'
import { ToolsSchema } from './tools.mts'
import { ReleaseRequestSchema, ReleaseReceiptSchema } from './release.mts'
import type { toStandaloneModule } from 'ata-validator/build'

export const SCHEMAS = {
  'external-tools': ToolsSchema,
  'release-request': ReleaseRequestSchema,
  'release-receipt': ReleaseReceiptSchema,
}
export const COMPILER_OPTIONS = {
  abortEarly: false,
  format: 'esm' as const,
  source: false,
  strictSchema: true,
  useDefaults: false,
}

export function compileValidator(schema: object) {
  const require = createRequire(import.meta.url)
  const compiler = require('ata-validator/build') as {
    toStandaloneModule: typeof toStandaloneModule
  }
  const warnings: string[] = []
  const output = compiler.toStandaloneModule(schema, {
    ...COMPILER_OPTIONS,
    onWarning: warning => warnings.push(warning),
  })
  if (!output || warnings.length) {
    throw new Error(`Validator compilation failed: ${warnings.join(', ')}`)
  }
  return (
    '// @ts-nocheck\n// @generated by scripts/repo/schema/run.mts.\n' + output
  )
}

export function formatGenerated(source: string, file: string) {
  return execFileSync(
    process.execPath,
    [
      path.join(REPO_ROOT, 'node_modules/oxfmt/bin/oxfmt'),
      '--config',
      path.join(REPO_ROOT, '.config/oxfmt.json'),
      '--stdin-filepath',
      file,
    ],
    {
      cwd: REPO_ROOT,
      input: source,
      encoding: 'utf8',
      maxBuffer: 8 * 1024 * 1024,
    },
  )
}

export function schemaArtifacts() {
  return Object.entries(SCHEMAS).flatMap(([name, schema]) => [
    {
      file: `.config/${name}.schema.json`,
      source: formatGenerated(
        JSON.stringify({
          $schema: 'https://json-schema.org/draft/2020-12/schema',
          ...schema,
        }),
        `${name}.json`,
      ),
    },
    {
      file: `.config/generated/${name}.mts`,
      source: formatGenerated(compileValidator(schema), `${name}.mts`),
    },
  ])
}

export function generateSchemas(check = false, root = REPO_ROOT) {
  for (const artifact of schemaArtifacts()) {
    const file = path.join(root, artifact.file)
    if (check) {
      if (readFileSync(file, 'utf8') !== artifact.source) {
        throw new Error(
          `Stale schema or validator: ${artifact.file}. Run pnpm run gen:schemas.`,
        )
      }
    } else {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, artifact.source)
    }
  }
}

export function main(args = process.argv.slice(2)) {
  if (args.includes('--help') || args.includes('-h')) {
    console.log('Usage: pnpm run gen:schemas [--check]')
    return
  }
  if (args.some(arg => arg !== '--check')) {
    throw new Error('Usage: pnpm run gen:schemas [--check]')
  }
  generateSchemas(args.includes('--check'))
}

if (isMainModule(import.meta.url)) {
  main()
}
