// Generated by scripts/repo/gen/type-union-route-decision.mts.
// Experimental candidate only. Its evaluation did not pass promotion.
export const typeUnionModelId = 'planner-2026-10-03' as const
export function chooseBroad(
  count: number,
  total: number,
  arity: number,
): boolean {
  // oxlint-disable eslint/no-unneeded-ternary -- The fixed model expression preserves its exported candidate behavior.
  return (arity === 2 || arity === 6) &&
    total >= 131 &&
    total <= 1155 &&
    count >= 2 &&
    count <= 819 &&
    count / total >= 0.013605442176870748 &&
    count / total <= 0.7974683544303798
    ? count / total <= 0.3937801496985959
      ? false
      : true
    : count > 0 && count * 3 > total
}
