import { readFileSync } from 'node:fs';
import { runScenarios } from './harness';

const html = readFileSync('test_new/browser/speed_selectors.html', 'utf8');

runScenarios('speed', 'normal', [
  {
    name: 'default',
    html,
    htmlMode: 'document',
    cases: [
      { selector: '#title' },
      { selector: 'h1#title' },
      { selector: 'div #title' },
      { selector: '#changes + #contents' },
      { selector: '.note' },
      { selector: 'div.note' },
      { selector: 'body .note' },
      { selector: '.no-toc + .toc' },
      { selector: 'div.example' },
      { selector: '.title' },
      { selector: '.toc' },
      { selector: 'p + .note' },
      { selector: 'div.example, p.note' },
      { selector: 'body' },
      { selector: 'div' },
      { selector: 'body div' },
      { selector: 'div p' },
      { selector: 'div > p' },
      { selector: 'div + p' },
      { selector: 'div ~ p' },
      { selector: 'div[class^=exa][class$=mple]' },
      { selector: 'p a' },
      { selector: 'div p a' },
      { selector: 'div > p > a' },
      { selector: 'div.example > p > a' },
      { selector: 'div + p + ul' },
      { selector: 'div ~ p ~ ul' },
      { selector: 'div, ul, a' },
      { selector: 'h1, h2, h3, h4, h5, h6' },
      { selector: 'a[href][lang][class]' },
      { selector: 'div[class]' },
      { selector: 'div[class=example]' },
      { selector: 'div[class^=exa]' },
      { selector: 'div[class$=mple]' },
      { selector: 'div[class*=e]' },
      { selector: 'div[class~=example]' },
      { selector: 'div:not(.example)' },
      { selector: 'div:nth-child(even)' },
      { selector: 'div:nth-child(2n)' },
      { selector: 'div:nth-child(odd)' },
      { selector: 'div:nth-child(2n+1)' },
      { selector: 'div:nth-child(n)' },
      { selector: 'p:only-child' },
      { selector: 'p:last-child' },
      { selector: 'p:first-child' },
    ],
  },
  {
    name: 'descendants_only',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'ul li a span' },
      { selector: 'ul li span' },
      { selector: 'li a span' },
      { selector: 'ul a span' },
      { selector: 'ul li a' },
      { selector: 'ul li' },
      { selector: 'li a' },
      { selector: 'ul a' },
      { selector: 'dl dt code' },
      { selector: 'dl dd a' },
      { selector: 'dl dd' },
      { selector: 'dl dt' },
      { selector: 'table tr td' },
      { selector: 'table tr' },
      { selector: 'tr td a' },
      { selector: 'td a' },
    ],
  },
  {
    name: 'descendant_and_siblings',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div ul li a span' },
      { selector: 'div ul li a' },
      { selector: 'div ul li' },
      { selector: 'div ul' },
      { selector: 'ul li a span' },
      { selector: 'ul li a' },
      { selector: 'ul li' },
      { selector: 'li a' },
      { selector: 'div > ul > li > a > span' },
      { selector: 'div > ul > li > a' },
      { selector: 'div > ul > li' },
      { selector: 'div > ul' },
      { selector: 'ul > li > a > span' },
      { selector: 'ul > li > a' },
      { selector: 'ul > li' },
      { selector: 'li > a' },
      { selector: 'h2 + p + ul + p' },
      { selector: 'h2 + p + ul' },
      { selector: 'p + ul + p' },
      { selector: 'li + li' },
      { selector: 'h2 + ul' },
      { selector: 'h2 + p' },
      { selector: 'ul + p' },
      { selector: 'p + p' },
      { selector: 'h2 ~ p ~ ul ~ p' },
      { selector: 'h2 ~ p ~ ul' },
      { selector: 'p ~ ul ~ p' },
      { selector: 'li ~ li' },
      { selector: 'h2 ~ ul' },
      { selector: 'h2 ~ p' },
      { selector: 'ul ~ p' },
      { selector: 'p ~ p' },
    ],
  },
  {
    name: 'tree-structural_child-indexed',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div:last-child' },
      { selector: 'div:only-child' },
      { selector: 'div:first-child' },
      { selector: 'div:nth-child(n)' },
      { selector: 'div:nth-child(3)' },
      { selector: 'div:nth-child(n+3)' },
      { selector: 'div:nth-child(+n-3)' },
      { selector: 'div:nth-child(2n)' },
      { selector: 'div:nth-child(odd)' },
      { selector: 'div:nth-child(2n+1)' },
      { selector: 'div:nth-child(even)' },
      { selector: 'div:nth-last-child(n)' },
      { selector: 'div:nth-last-child(3)' },
      { selector: 'div:nth-last-child(n+3)' },
      { selector: 'div:nth-last-child(+n-3)' },
      { selector: 'div:nth-last-child(2n)' },
      { selector: 'div:nth-last-child(odd)' },
      { selector: 'div:nth-last-child(2n+1)' },
      { selector: 'div:nth-last-child(even)' },
    ],
  },
  {
    name: 'tree-structural_typed_child-indexed',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div:last-of-type' },
      { selector: 'div:only-of-type' },
      { selector: 'div:first-of-type' },
      { selector: 'div:nth-of-type(n)' },
      { selector: 'div:nth-of-type(3)' },
      { selector: 'div:nth-of-type(n+3)' },
      { selector: 'div:nth-of-type(+n-3)' },
      { selector: 'div:nth-of-type(2n)' },
      { selector: 'div:nth-of-type(odd)' },
      { selector: 'div:nth-of-type(2n+1)' },
      { selector: 'div:nth-of-type(even)' },
      { selector: 'div:nth-last-of-type(n)' },
      { selector: 'div:nth-last-of-type(3)' },
      { selector: 'div:nth-last-of-type(n+3)' },
      { selector: 'div:nth-last-of-type(+n-3)' },
      { selector: 'div:nth-last-of-type(2n)' },
      { selector: 'div:nth-last-of-type(odd)' },
      { selector: 'div:nth-last-of-type(2n+1)' },
      { selector: 'div:nth-last-of-type(even)' },
    ],
  },
  {
    name: 'comma-separated_group_or_selector_list',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div, ul, li, a' },
      { selector: 'div, ul, li' },
      { selector: 'ul, li, a' },
      { selector: 'div, li' },
      { selector: 'div, a' },
      { selector: 'ul, li' },
      { selector: 'ul, a' },
      { selector: 'li, a' },
      { selector: 'div, p, a, em' },
      { selector: 'div, p, em' },
      { selector: 'div, p, a' },
      { selector: 'div, p' },
      { selector: 'div, a' },
      { selector: 'p, em' },
      { selector: 'a, em' },
      { selector: 'p, a' },
    ],
  },

  {
    name: 'negation_tree-structural_child-indexed',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div:not(:last-child)' },
      { selector: 'div:not(:only-child)' },
      { selector: 'div:not(:first-child)' },
      { selector: 'div:not(:nth-child(n))' },
      { selector: 'div:not(:nth-child(3))' },
      { selector: 'div:not(:nth-child(n+3))' },
      { selector: 'div:not(:nth-child(+n-3))' },
      { selector: 'div:not(:nth-child(2n))' },
      { selector: 'div:not(:nth-child(odd))' },
      { selector: 'div:not(:nth-child(2n+1))' },
      { selector: 'div:not(:nth-child(even))' },
      { selector: 'div:not(:nth-last-child(n))' },
      { selector: 'div:not(:nth-last-child(3))' },
      { selector: 'div:not(:nth-last-child(n+3))' },
      { selector: 'div:not(:nth-last-child(+n-3))' },
      { selector: 'div:not(:nth-last-child(2n))' },
      { selector: 'div:not(:nth-last-child(odd))' },
      { selector: 'div:not(:nth-last-child(2n+1))' },
      { selector: 'div:not(:nth-last-child(even))' },
    ],
  },
  {
    name: 'negation_tree-structural_typed_child-indexed',
    html,
    htmlMode: 'document',
    cases: [
      { selector: 'div:not(:last-of-type)' },
      { selector: 'div:not(:only-of-type)' },
      { selector: 'div:not(:first-of-type)' },
      { selector: 'div:not(:nth-of-type(n))' },
      { selector: 'div:not(:nth-of-type(3))' },
      { selector: 'div:not(:nth-of-type(n+3))' },
      { selector: 'div:not(:nth-of-type(+n-3))' },
      { selector: 'div:not(:nth-of-type(2n))' },
      { selector: 'div:not(:nth-of-type(odd))' },
      { selector: 'div:not(:nth-of-type(2n+1))' },
      { selector: 'div:not(:nth-of-type(even))' },
      { selector: 'div:not(:nth-last-of-type(n))' },
      { selector: 'div:not(:nth-last-of-type(3))' },
      { selector: 'div:not(:nth-last-of-type(n+3))' },
      { selector: 'div:not(:nth-last-of-type(+n-3))' },
      { selector: 'div:not(:nth-last-of-type(2n))' },
      { selector: 'div:not(:nth-last-of-type(odd))' },
      { selector: 'div:not(:nth-last-of-type(2n+1))' },
      { selector: 'div:not(:nth-last-of-type(even))' },
    ],
  },
  {
    name: 'matches_and_negation_dynamic_and_user_actions',
    html,
    htmlMode: 'document',
    cases: [
      { selector: ':lang(fr)' },
      { selector: ':visited' },
      { selector: ':target' },
      // { selector: ':active' },
      { selector: ':hover' },
      // { selector: ':focus' },
      { selector: ':empty' },
      { selector: ':link' },
      { selector: ':not(:lang(fr))' },
      { selector: ':not(:visited)' },
      { selector: ':not(:target)' },
      // { selector: ':not(:active)' },
      { selector: ':not(:hover)' },
      // { selector: ':not(:focus)' },
      { selector: ':not(:empty)' },
      { selector: ':not(:link)' },
    ],
  },
  {
    // active/focus does not seem to be stable. also, not supported in any of the browsers.
    name: 'matches_and_negation_dynamic_and_user_actions - active/focus',
    modifier: 'fixme',
    html,
    htmlMode: 'document',
    cases: [
      { selector: ':active' },
      { selector: ':focus' },
      { selector: ':not(:active)' },
      { selector: ':not(:focus)' },
    ],
  },

]);