name: nwsapi

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: latest
        package-manager-cache: false

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
